--- #YAML:1.0
name:               PDL-EditDistance
version:            0.05001
abstract:           Compute Wagner-Fischer edit distance and alignment matrices on PDLs
author:
    - Bryan Jurish
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    PDL:  2.4.2
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
